# See https://just.systems for more information.

build:
  # Build the component with cargo-compoenent
  RUSTFLAGS='--cfg getrandom_backend="custom"' cargo component build --target wasm32-unknown-unknown --release

test: build 
  cargo test

