check:
  cargo check
  cargo check --all --all-targets
  cargo check --all --all-targets --target wasm32-unknown-unknown

# Install required targets
install-targets:
    rustup target add wasm32-unknown-unknown aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
