check32:
  RUSTFLAGS='--cfg getrandom_backend="wasm_js"' cargo check --target wasm32-unknown-unknown

test: test-web 
  cargo test

test-web:
  RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack build --target web
  RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack test --chrome --all-features
